create table if not exists private.snar_question_reports (
  id bigint generated by default as identity primary key,
  reason text not null check (reason in ('Wrong answer','Ambiguous question','Typo / wording','Explanation issue','Source / citation issue','Image / figure issue','Other')),
  status text not null default 'new' check (status in ('new','reviewing','fixed','declined')),
  question_uid text not null check (char_length(question_uid) between 1 and 160),
  bank text not null check (char_length(bank) between 1 and 80),
  bank_label text not null default '',
  set_label text not null default '',
  question_number text not null default '',
  topic text not null default '',
  stem text not null check (char_length(stem) between 1 and 4000),
  options jsonb not null default '[]'::jsonb,
  answer_indexes jsonb not null default '[]'::jsonb,
  answer_text jsonb not null default '[]'::jsonb,
  selected_indexes jsonb not null default '[]'::jsonb,
  selected_text jsonb not null default '[]'::jsonb,
  explanation text not null default '',
  source text not null default '',
  page text not null default '',
  page_url text not null default '',
  build text not null default '',
  comment text not null check (char_length(comment) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
revoke all on table private.snar_question_reports from public, anon, authenticated;

create or replace function public.snar_submit_question_report(p_report jsonb)
returns bigint language plpgsql security definer set search_path=''
as $$
declare
  uid uuid := auth.uid();
  rid bigint;
  r text := trim(coalesce(p_report->>'reason',''));
  qid text := trim(coalesce(p_report->>'uid',''));
  b text := trim(coalesce(p_report->>'bank',''));
  s text := trim(coalesce(p_report->>'stem',''));
  c text := trim(coalesce(p_report->>'comment',''));
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if not private.snar_account_is_active(uid) then raise exception 'Account access suspended'; end if;
  if r not in ('Wrong answer','Ambiguous question','Typo / wording','Explanation issue','Source / citation issue','Image / figure issue','Other') then raise exception 'Invalid report reason'; end if;
  if char_length(qid) < 1 or char_length(qid) > 160 then raise exception 'Invalid question id'; end if;
  if char_length(b) < 1 or char_length(b) > 80 then raise exception 'Invalid bank'; end if;
  if char_length(s) < 1 or char_length(s) > 4000 then raise exception 'Invalid question stem'; end if;
  if char_length(c) < 1 or char_length(c) > 2000 then raise exception 'Invalid report comment'; end if;

  insert into private.snar_question_reports(
    reason,question_uid,bank,bank_label,set_label,question_number,topic,stem,
    options,answer_indexes,answer_text,selected_indexes,selected_text,
    explanation,source,page,page_url,build,comment
  ) values (
    r,qid,b,left(coalesce(p_report->>'bankLabel',''),200),left(coalesce(p_report->>'set',''),80),
    left(coalesce(p_report->>'questionNumber',''),80),left(coalesce(p_report->>'topic',''),200),s,
    case when jsonb_typeof(p_report->'options')='array' then p_report->'options' else '[]'::jsonb end,
    case when jsonb_typeof(p_report->'answerIndexes')='array' then p_report->'answerIndexes' else '[]'::jsonb end,
    case when jsonb_typeof(p_report->'answerText')='array' then p_report->'answerText' else '[]'::jsonb end,
    case when jsonb_typeof(p_report->'selectedIndexes')='array' then p_report->'selectedIndexes' else '[]'::jsonb end,
    case when jsonb_typeof(p_report->'selectedText')='array' then p_report->'selectedText' else '[]'::jsonb end,
    left(coalesce(p_report->>'explanation',''),8000),left(coalesce(p_report->>'source',''),2000),
    left(coalesce(p_report->>'page',''),200),left(coalesce(p_report->>'pageUrl',''),1000),
    left(coalesce(p_report->>'build',''),200),c
  ) returning id into rid;
  return rid;
end;
$$;
revoke all on function public.snar_submit_question_report(jsonb) from public, anon;
grant execute on function public.snar_submit_question_report(jsonb) to authenticated;

create or replace function public.snar_admin_question_reports()
returns table(
  id bigint, reason text, status text, question_uid text, bank text, bank_label text,
  set_label text, question_number text, topic text, stem text, options jsonb,
  answer_indexes jsonb, answer_text jsonb, selected_indexes jsonb, selected_text jsonb,
  explanation text, source text, page text, page_url text, build text, comment text,
  created_at timestamptz, updated_at timestamptz
) language plpgsql stable security definer set search_path=''
as $$
begin
  if not private.snar_is_admin(auth.uid()) then raise exception 'Admin required'; end if;
  return query
    select r.id,r.reason,r.status,r.question_uid,r.bank,r.bank_label,r.set_label,r.question_number,
           r.topic,r.stem,r.options,r.answer_indexes,r.answer_text,r.selected_indexes,r.selected_text,
           r.explanation,r.source,r.page,r.page_url,r.build,r.comment,r.created_at,r.updated_at
    from private.snar_question_reports r
    order by case r.status when 'new' then 0 when 'reviewing' then 1 else 2 end, r.created_at desc;
end;
$$;
revoke all on function public.snar_admin_question_reports() from public, anon;
grant execute on function public.snar_admin_question_reports() to authenticated;

create or replace function public.snar_admin_update_question_report(p_id bigint,p_status text)
returns boolean language plpgsql security definer set search_path=''
as $$
declare n integer;
begin
  if not private.snar_is_admin(auth.uid()) then raise exception 'Admin required'; end if;
  if p_status not in ('new','reviewing','fixed','declined') then raise exception 'Invalid report status'; end if;
  update private.snar_question_reports set status=p_status,updated_at=now() where id=p_id;
  get diagnostics n=row_count;
  return n=1;
end;
$$;
revoke all on function public.snar_admin_update_question_report(bigint,text) from public, anon;
grant execute on function public.snar_admin_update_question_report(bigint,text) to authenticated;

create or replace function public.snar_admin_system_summary()
returns jsonb language plpgsql stable security definer set search_path=''
as $$
declare out jsonb;
begin
  if not private.snar_is_admin(auth.uid()) then raise exception 'Admin required'; end if;
  select jsonb_build_object(
    'accounts',(select count(*) from auth.users),
    'active_accounts',(select count(*) from auth.users u where private.snar_account_is_active(u.id)),
    'suspended_accounts',(select count(*) from auth.users u where not private.snar_account_is_active(u.id)),
    'legal_acceptances',(select count(*) from private.snar_legal_acceptances),
    'privacy_requests',(select count(*) from public.snar_privacy_requests),
    'privacy_received',(select count(*) from public.snar_privacy_requests where status='received'),
    'privacy_in_review',(select count(*) from public.snar_privacy_requests where status='in_review'),
    'suggestions',(select count(*) from private.snar_suggestions),
    'new_suggestions',(select count(*) from private.snar_suggestions where status='new'),
    'question_reports',(select count(*) from private.snar_question_reports),
    'new_question_reports',(select count(*) from private.snar_question_reports where status='new'),
    'item_contributions',(select count(*) from private.mbu_item_contributions),
    'calibrated_items_any',(select count(*) from public.mbu_item_calibration where unique_learners>=1),
    'calibrated_items_2',(select count(*) from public.mbu_item_calibration where unique_learners>=2),
    'calibrated_items_5',(select count(*) from public.mbu_item_calibration where unique_learners>=5),
    'calibrated_items_25',(select count(*) from public.mbu_item_calibration where unique_learners>=25),
    'calibration_max_learners',(select coalesce(max(unique_learners),0) from public.mbu_item_calibration),
    'calibration_first_attempts',(select coalesce(sum(correct_first_attempts+incorrect_first_attempts),0) from public.mbu_item_calibration),
    'sync_state_rows',(select count(*) from public.mbu_sync_state),
    'sync_history_rows',(select count(*) from public.mbu_sync_versions),
    'guest_active_15m',(select count(*) from private.snar_guest_sessions where last_seen_at>=now()-interval '15 minutes'),
    'guest_sessions_24h',(select count(*) from private.snar_guest_sessions where last_seen_at>=now()-interval '24 hours'),
    'cat_users',(select count(distinct user_id) from private.mbu_item_contributions where session_mode='adaptive'),
    'adaptive_first_attempts',(select count(*) from private.mbu_item_contributions where session_mode='adaptive')
  ) into out;
  return out;
end;
$$;
revoke all on function public.snar_admin_system_summary() from public, anon;
grant execute on function public.snar_admin_system_summary() to authenticated;
